name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Python tests
        run: |
          cd Python/test
          pytest

      - name: Build C solutions
        run: |
          sudo apt-get install -y cmake
          cd C
          mkdir build && cd build
          cmake ..
          make

      - name: Run C tests
        run: |
          cd C/build
          for test in test_*; do ./$test; done
